# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Malcolm King'
tagline:          'Mandatory web prescence'
description:      'Research Fellow at Monash University, also does other stuff.'
# url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Malcolm King'
  url:            https://malcolmking.github.io

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#  repo:           https://github.com/poole/hyde
